static NSString * const kEmbeddedGlyphMetalSource = @"// ─── Ed Glyph Shader — Instanced Text Rendering ────────────────────────────\n"
@"//\n"
@"// Renders monospaced text via instanced quads. Each instance represents one\n"
@"// character cell with:\n"
@"//   - Screen position (pixels, top-left of cell)\n"
@"//   - Glyph atlas UV (pixels, top-left of glyph in atlas)\n"
@"//   - Foreground colour (RGBA u8)\n"
@"//   - Background colour (RGBA u8)\n"
@"//   - Flags (underline, bold, cursor, wavy underline, selection, inverse)\n"
@"//\n"
@"// The vertex shader positions a unit quad per instance and computes texture\n"
@"// coordinates. The fragment shader samples the glyph atlas alpha mask and\n"
@"// composites foreground over background.\n"
@"//\n"
@"// A single draw call renders all visible text: editor, gutter, terminal, etc.\n"
@"\n"
@"#include <metal_stdlib>\n"
@"using namespace metal;\n"
@"\n"
@"// ─── Shared Types (must match platform.zig GlyphInstance / EdUniforms) ──────\n"
@"\n"
@"struct GlyphInstance {\n"
@"    float pos_x;        // screen pos X (pixels, top-left)\n"
@"    float pos_y;        // screen pos Y (pixels, top-left)\n"
@"    float uv_x;         // atlas UV X (pixels, top-left of glyph)\n"
@"    float uv_y;         // atlas UV Y (pixels, top-left of glyph)\n"
@"    uchar4 fg;          // foreground RGBA\n"
@"    uchar4 bg;          // background RGBA\n"
@"    uint   flags;       // bit flags\n"
@"};\n"
@"\n"
@"struct EdUniforms {\n"
@"    float viewport_width;\n"
@"    float viewport_height;\n"
@"    float cell_width;\n"
@"    float cell_height;\n"
@"    float atlas_width;\n"
@"    float atlas_height;\n"
@"    float time;\n"
@"    float effects_mode; // 0=none, 1=crt, 2=scanlines\n"
@"};\n"
@"\n"
@"// Flag constants (must match platform.zig)\n"
@"constant uint FLAG_UNDERLINE      = 1u << 0;\n"
@"constant uint FLAG_BOLD           = 1u << 1;\n"
@"constant uint FLAG_CURSOR         = 1u << 2;\n"
@"constant uint FLAG_STRIKETHROUGH  = 1u << 3;\n"
@"constant uint FLAG_WAVY_UNDERLINE = 1u << 4;\n"
@"constant uint FLAG_SELECTION      = 1u << 5;\n"
@"constant uint FLAG_INVERSE        = 1u << 6;\n"
@"\n"
@"// ─── Vertex Output ──────────────────────────────────────────────────────────\n"
@"\n"
@"struct VertexOut {\n"
@"    float4 position [[position]];\n"
@"    float2 tex_coord;\n"
@"    float4 fg_color;\n"
@"    float4 bg_color;\n"
@"    uint   flags;\n"
@"    float2 cell_pos;      // position within the cell (0..1, 0..1)\n"
@"    float  cell_width;\n"
@"    float  cell_height;\n"
@"    float  time;\n"
@"    float2 screen_pos;    // screen position in normalized coords (0..1)\n"
@"    float  effects_mode;\n"
@"};\n"
@"\n"
@"// ─── Vertex Shader ──────────────────────────────────────────────────────────\n"
@"\n"
@"vertex VertexOut glyph_vertex(\n"
@"    uint vertex_id      [[vertex_id]],\n"
@"    uint instance_id    [[instance_id]],\n"
@"    const device GlyphInstance* instances [[buffer(0)]],\n"
@"    constant EdUniforms& uniforms        [[buffer(1)]]\n"
@") {\n"
@"    // Unit quad: two triangles covering (0,0) to (1,1)\n"
@"    // Triangle 1: (0,0), (1,0), (0,1)\n"
@"    // Triangle 2: (1,0), (1,1), (0,1)\n"
@"    float2 quad_positions[6] = {\n"
@"        float2(0.0, 0.0),\n"
@"        float2(1.0, 0.0),\n"
@"        float2(0.0, 1.0),\n"
@"        float2(1.0, 0.0),\n"
@"        float2(1.0, 1.0),\n"
@"        float2(0.0, 1.0)\n"
@"    };\n"
@"\n"
@"    float2 quad_pos = quad_positions[vertex_id];\n"
@"    GlyphInstance inst = instances[instance_id];\n"
@"\n"
@"    // Screen position: instance position + quad corner * cell size\n"
@"    float2 screen_pos = float2(inst.pos_x, inst.pos_y) + quad_pos * float2(uniforms.cell_width, uniforms.cell_height);\n"
@"\n"
@"    // Convert to NDC: (0,0) = top-left, (w,h) = bottom-right → (-1,1) to (1,-1)\n"
@"    float2 ndc;\n"
@"    ndc.x = (screen_pos.x / uniforms.viewport_width)  *  2.0 - 1.0;\n"
@"    ndc.y = (screen_pos.y / uniforms.viewport_height) * -2.0 + 1.0;\n"
@"\n"
@"    // Texture coordinate: atlas UV + quad corner * cell size, normalised to atlas size\n"
@"    float2 tex_coord;\n"
@"    tex_coord.x = (inst.uv_x + quad_pos.x * uniforms.cell_width)  / uniforms.atlas_width;\n"
@"    tex_coord.y = (inst.uv_y + quad_pos.y * uniforms.cell_height) / uniforms.atlas_height;\n"
@"\n"
@"    // Convert uchar4 colours to float4 (0.0–1.0)\n"
@"    float4 fg = float4(inst.fg) / 255.0;\n"
@"    float4 bg = float4(inst.bg) / 255.0;\n"
@"\n"
@"    // Handle inverse flag: swap fg and bg\n"
@"    if (inst.flags & FLAG_INVERSE) {\n"
@"        float4 tmp = fg;\n"
@"        fg = bg;\n"
@"        bg = tmp;\n"
@"        fg.a = 1.0;\n"
@"        bg.a = 1.0;\n"
@"    }\n"
@"\n"
@"    VertexOut out;\n"
@"    out.position    = float4(ndc, 0.0, 1.0);\n"
@"    out.tex_coord   = tex_coord;\n"
@"    out.fg_color    = fg;\n"
@"    out.bg_color    = bg;\n"
@"    out.flags       = inst.flags;\n"
@"    out.cell_pos    = quad_pos;\n"
@"    out.cell_width  = uniforms.cell_width;\n"
@"    out.cell_height = uniforms.cell_height;\n"
@"    out.time        = uniforms.time;\n"
@"    out.screen_pos  = screen_pos / float2(uniforms.viewport_width, uniforms.viewport_height);\n"
@"    out.effects_mode = uniforms.effects_mode;\n"
@"    return out;\n"
@"}\n"
@"\n"
@"// ─── CRT Effect Helper Functions ────────────────────────────────────────────\n"
@"\n"
@"/// Scanline effect (horizontal lines across the screen).\n"
@"float crt_scanlines(float2 screen_pos, float viewport_height) {\n"
@"    float line = screen_pos.y * viewport_height;\n"
@"    float scanline = sin(line * 3.14159);\n"
@"    scanline = scanline * 0.5 + 0.5;\n"
@"    scanline = pow(scanline, 3.0);\n"
@"    return mix(1.0, scanline, 0.25); // 0.25 = intensity\n"
@"}\n"
@"\n"
@"/// Vignette effect (darken corners).\n"
@"float crt_vignette(float2 screen_pos) {\n"
@"    float2 centered = screen_pos * 2.0 - 1.0;\n"
@"    float dist = length(centered);\n"
@"    float vig = smoothstep(1.4, 0.5, dist);\n"
@"    return mix(1.0, vig, 0.4); // 0.4 = strength\n"
@"}\n"
@"\n"
@"/// Phosphor glow effect (brighten high-intensity areas).\n"
@"float3 crt_glow(float3 color) {\n"
@"    float brightness = dot(color, float3(0.299, 0.587, 0.114));\n"
@"    float glow = pow(brightness, 2.0) * 0.15; // 0.15 = glow strength\n"
@"    return color + float3(glow);\n"
@"}\n"
@"\n"
@"// ─── Fragment Shader ────────────────────────────────────────────────────────\n"
@"\n"
@"fragment float4 glyph_fragment(\n"
@"    VertexOut in [[stage_in]],\n"
@"    texture2d<float> atlas [[texture(0)]],\n"
@"    sampler atlas_sampler   [[sampler(0)]]\n"
@") {\n"
@"    // Sample glyph alpha from the atlas\n"
@"    float glyph_alpha = atlas.sample(atlas_sampler, in.tex_coord).a;\n"
@"\n"
@"    // Bold: thicken the glyph by biasing the alpha\n"
@"    if (in.flags & FLAG_BOLD) {\n"
@"        glyph_alpha = saturate(glyph_alpha * 1.4 + 0.05);\n"
@"    }\n"
@"\n"
@"    // Composite: foreground over background using glyph alpha\n"
@"    float4 color = mix(in.bg_color, in.fg_color, glyph_alpha);\n"
@"\n"
@"    // ── Cursor overlay ──────────────────────────────────────────────────\n"
@"    if (in.flags & FLAG_CURSOR) {\n"
@"        // Block cursor with blink: 530ms on, 530ms off\n"
@"        float blink = step(0.0, sin(in.time * 3.14159 / 0.53));\n"
@"        if (blink > 0.5) {\n"
@"            // Semi-transparent cursor overlay\n"
@"            float4 cursor_color = in.fg_color;\n"
@"            cursor_color.a = 0.7;\n"
@"            color = mix(color, cursor_color, cursor_color.a);\n"
@"        }\n"
@"    }\n"
@"\n"
@"    // ── Selection highlight ─────────────────────────────────────────────\n"
@"    if (in.flags & FLAG_SELECTION) {\n"
@"        // Blend a selection tint over the background\n"
@"        // The selection colours are already set in bg, so just ensure visibility\n"
@"        color = mix(in.bg_color, in.fg_color, glyph_alpha);\n"
@"    }\n"
@"\n"
@"    // ── Underline ───────────────────────────────────────────────────────\n"
@"    if (in.flags & FLAG_UNDERLINE) {\n"
@"        // Draw a 1px underline at ~90% of cell height\n"
@"        float underline_y = 0.9;\n"
@"        float underline_thickness = 1.0 / in.cell_height;\n"
@"        if (in.cell_pos.y > underline_y && in.cell_pos.y < underline_y + underline_thickness * 2.0) {\n"
@"            color = in.fg_color;\n"
@"        }\n"
@"    }\n"
@"\n"
@"    // ── Wavy underline (errors) ─────────────────────────────────────────\n"
@"    if (in.flags & FLAG_WAVY_UNDERLINE) {\n"
@"        float underline_y = 0.88;\n"
@"        // Wavy: sine wave along x, 2 cycles per cell\n"
@"        float wave = sin(in.cell_pos.x * 3.14159 * 4.0) * 0.03;\n"
@"        float y_dist = abs(in.cell_pos.y - (underline_y + wave));\n"
@"        float thickness = 1.5 / in.cell_height;\n"
@"        if (y_dist < thickness) {\n"
@"            // Error red colour — uses the fg_color which should be set to error colour\n"
@"            float wave_alpha = 1.0 - (y_dist / thickness);\n"
@"            float4 wave_color = float4(1.0, 0.3, 0.3, wave_alpha);\n"
@"            color = mix(color, wave_color, wave_alpha);\n"
@"        }\n"
@"    }\n"
@"\n"
@"    // ── Strikethrough ───────────────────────────────────────────────────\n"
@"    if (in.flags & FLAG_STRIKETHROUGH) {\n"
@"        float strike_y = 0.45;\n"
@"        float strike_thickness = 1.0 / in.cell_height;\n"
@"        if (in.cell_pos.y > strike_y && in.cell_pos.y < strike_y + strike_thickness * 2.0) {\n"
@"            color = in.fg_color;\n"
@"        }\n"
@"    }\n"
@"\n"
@"    // ── CRT Effects (if enabled) ────────────────────────────────────────\n"
@"    if (in.effects_mode >= 1.0) {\n"
@"        // Apply scanlines\n"
@"        float scanline_factor = crt_scanlines(in.screen_pos, 1600.0); // Approx height\n"
@"        color.rgb *= scanline_factor;\n"
@"\n"
@"        // Apply vignette\n"
@"        float vignette_factor = crt_vignette(in.screen_pos);\n"
@"        color.rgb *= vignette_factor;\n"
@"\n"
@"        // Apply phosphor glow (for CRT mode only, not scanlines-only)\n"
@"        if (in.effects_mode >= 1.0 && in.effects_mode < 2.0) {\n"
@"            color.rgb = crt_glow(color.rgb);\n"
@"        }\n"
@"\n"
@"        // Add subtle noise/grain\n"
@"        float grain = fract(sin(dot(in.screen_pos + in.time * 0.001, float2(12.9898, 78.233))) * 43758.5453);\n"
@"        color.rgb += (grain - 0.5) * 0.015;\n"
@"\n"
@"        // Subtle flicker\n"
@"        float flicker = 1.0 + sin(in.time * 120.0) * 0.003;\n"
@"        color.rgb *= flicker;\n"
@"\n"
@"        // Clamp\n"
@"        color.rgb = saturate(color.rgb);\n"
@"    }\n"
@"\n"
@"    return color;\n"
@"}\n"
@"\n"
@"// ─── Minimap Shader ─────────────────────────────────────────────────────────\n"
@"//\n"
@"// The minimap uses the same instance format but renders at a much smaller scale.\n"
@"// Each \"character\" becomes a tiny coloured dot. No atlas sampling needed.\n"
@"\n"
@"struct MinimapVertexOut {\n"
@"    float4 position [[position]];\n"
@"    float4 color;\n"
@"};\n"
@"\n"
@"vertex MinimapVertexOut minimap_vertex(\n"
@"    uint vertex_id      [[vertex_id]],\n"
@"    uint instance_id    [[instance_id]],\n"
@"    const device GlyphInstance* instances [[buffer(0)]],\n"
@"    constant EdUniforms& uniforms        [[buffer(1)]]\n"
@") {\n"
@"    float2 quad_positions[6] = {\n"
@"        float2(0.0, 0.0),\n"
@"        float2(1.0, 0.0),\n"
@"        float2(0.0, 1.0),\n"
@"        float2(1.0, 0.0),\n"
@"        float2(1.0, 1.0),\n"
@"        float2(0.0, 1.0)\n"
@"    };\n"
@"\n"
@"    float2 quad_pos = quad_positions[vertex_id];\n"
@"    GlyphInstance inst = instances[instance_id];\n"
@"\n"
@"    // Minimap cells are tiny (e.g., 2x2 pixels)\n"
@"    float2 screen_pos = float2(inst.pos_x, inst.pos_y) + quad_pos * float2(uniforms.cell_width, uniforms.cell_height);\n"
@"\n"
@"    float2 ndc;\n"
@"    ndc.x = (screen_pos.x / uniforms.viewport_width)  *  2.0 - 1.0;\n"
@"    ndc.y = (screen_pos.y / uniforms.viewport_height) * -2.0 + 1.0;\n"
@"\n"
@"    // Use the foreground colour directly (no atlas sampling)\n"
@"    float4 fg = float4(inst.fg) / 255.0;\n"
@"\n"
@"    MinimapVertexOut out;\n"
@"    out.position = float4(ndc, 0.0, 1.0);\n"
@"    out.color    = fg;\n"
@"    return out;\n"
@"}\n"
@"\n"
@"fragment float4 minimap_fragment(MinimapVertexOut in [[stage_in]]) {\n"
@"    return in.color;\n"
@"}\n"
@"\n"
@"// ─── Solid Rect Shader ──────────────────────────────────────────────────────\n"
@"//\n"
@"// For drawing solid rectangles: cursor blocks, selection highlights, dividers,\n"
@"// scrollbar elements, find highlights, etc. Uses the same instance buffer\n"
@"// format but ignores the atlas UV — just draws a solid bg-coloured rect.\n"
@"\n"
@"struct SolidVertexOut {\n"
@"    float4 position [[position]];\n"
@"    float4 color;\n"
@"};\n"
@"\n"
@"vertex SolidVertexOut solid_vertex(\n"
@"    uint vertex_id      [[vertex_id]],\n"
@"    uint instance_id    [[instance_id]],\n"
@"    const device GlyphInstance* instances [[buffer(0)]],\n"
@"    constant EdUniforms& uniforms        [[buffer(1)]]\n"
@") {\n"
@"    float2 quad_positions[6] = {\n"
@"        float2(0.0, 0.0),\n"
@"        float2(1.0, 0.0),\n"
@"        float2(0.0, 1.0),\n"
@"        float2(1.0, 0.0),\n"
@"        float2(1.0, 1.0),\n"
@"        float2(0.0, 1.0)\n"
@"    };\n"
@"\n"
@"    float2 quad_pos = quad_positions[vertex_id];\n"
@"    GlyphInstance inst = instances[instance_id];\n"
@"\n"
@"    // The \"cell size\" for solid rects is encoded in the UV field:\n"
@"    // uv_x = rect width, uv_y = rect height\n"
@"    float2 screen_pos = float2(inst.pos_x, inst.pos_y) + quad_pos * float2(inst.uv_x, inst.uv_y);\n"
@"\n"
@"    float2 ndc;\n"
@"    ndc.x = (screen_pos.x / uniforms.viewport_width)  *  2.0 - 1.0;\n"
@"    ndc.y = (screen_pos.y / uniforms.viewport_height) * -2.0 + 1.0;\n"
@"\n"
@"    float4 color = float4(inst.bg) / 255.0;\n"
@"\n"
@"    SolidVertexOut out;\n"
@"    out.position = float4(ndc, 0.0, 1.0);\n"
@"    out.color    = color;\n"
@"    return out;\n"
@"}\n"
@"\n"
@"fragment float4 solid_fragment(SolidVertexOut in [[stage_in]]) {\n"
@"    return in.color;\n"
@"}\n"
@"";